*** SLURM BATCH JOB 'part_1_train' STARTING ***
*** Activating environment cs236781-hw ***
[NbConvertApp] Converting notebook /home/aviv.shitrit/Deep_Learning_hw3/Part1_Sequence.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Timeout waiting for execute reply (3600s).
Traceback (most recent call last):
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 609, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nest_asyncio.py", line 96, in run_until_complete
    return f.result()
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 816, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 633, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/aviv.shitrit/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 683, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 3600 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['from cs236781.plot import plot_fit', '', 'def post_epoch_fn(epoch, train_res, test_res, verbose):', '    # Update learning rate', '    scheduler.step(test_res.accuracy)']
...
['                              checkpoints=checkpoint_file, print_every=1)', '        ', '        fig, axes = plot_fit(fit_res)', '    except KeyboardInterrupt as e:', "        print('\\n *** Training interrupted by user')"]
-------------------

Got errors while executing notebook /home/aviv.shitrit/Deep_Learning_hw3/Part1_Sequence.ipynb. Make sure you've implemented everything and that all tests pass.
>> Running 1 notebooks...
>> Running nbconvert on notebook /home/aviv.shitrit/Deep_Learning_hw3/Part1_Sequence.ipynb [execute|inplace]
*** SLURM BATCH JOB 'part_1_train' DONE ***
